### ISSUE TITLE
How to get permissions using polkit?

### ISSUE THREAD

**Issue by probonopd** [s3rj1k/go-fanotify#1]
Hi, I want to use fanotify in a GUI Go program.

How can I get permission to watch the filesystem using fanotify from polkit?

Something along those lines:

```

import (
(...)
	"github.com/amenzhinsky/go-polkit"
	"github.com/s3rj1k/go-fanotify/fanotify"
)

(...)
	// Get permission from polkit
	authority, err := polkit.NewAuthority()
	if err != nil {
		helpers.PrintError("fanotifymonitor: polkit.NewAuthority", err)
	}
	action := "org.freedesktop.policykit.exec"
	// FIXME: Looks like there is no action for fanotify
	// Can we get root directly, e.g., using auth_admin_keep without a /etc/polkit-1/rules.d/51-pkexec-auth-admin-keep.rules file?
	// Alternatively, can we get permission from polkit to write that file there?
	result, err := authority.CheckAuthorization(action, nil, polkit.CheckAuthorizationAllowUserInteraction, "")
	if err != nil {
		helpers.PrintError("fanotifymonitor: polkit.CheckAuthorization", err)
	}

	log.Printf("polkit: Is authorized: %t %s\n", result.IsAuthorized, action)

	// Run fanotify...
```

**Comment by s3rj1k** [comment]
Hi, @probonopd , never used polkit from golang before, however upon quick glance at a man page, seems the simple approach would be to just `pkexec` fanotify compiled code.

Also `https://www.freedesktop.org/software/polkit/docs/latest/polkit.8.html` states that custom auth helper can be used.

```
polkit.addRule(function(action, subject) {
    if (action.id == "org.freedesktop.policykit.exec" &&
        action.lookup("program") == "/usr/bin/cat") {
        return polkit.Result.AUTH_ADMIN;
    }
});
```

Hope this helps a bit.

P.S. I would consider going with client-server approach, server side is for fanotify, client is for GUI and auth. That way code will be more maintainable.

**Comment by probonopd** [comment]
I think that `org.freedesktop.policykit.exec` doesn't give us root rights. That is my problem; otherwise my code should work...

**Comment by s3rj1k** [comment]
@probonopd  can you actually run something as root?
root login in Ubuntu for example is disable by default.
Test with `su - root`

**Comment by probonopd** [comment]
Yes, I can run things as root on my system. I do not want to need an additional polkit file, because my users should not have to install anyting into system directories such as `/etc` or `/usr`.

**Comment by s3rj1k** [comment]
@probonopd I don't see any possible way of enabling running application as root with poolkit without adding additional files to `/etc/` or `/usr`.

Moreover I do not see any problem with adding those files when application is distributed to targeted users via native packaging, `deb`, `rpm`, `apk` ... or any other system for distributing prebuild packages, like `snap` or `flatpack`.

Your problem lies beyond the scope of this repository, so closing this issue.
