### ISSUE TITLE
Risk of double fd-close when using both `EventMetadata.Close()` and `EventMetadata.File()`

### ISSUE THREAD

**Issue by alban** [s3rj1k/go-fanotify#5]
When receiving an event from `NotifyFD.GetEvent()`, the file descriptor must be closed to avoid a fd leak. There is a method `EventMetadata.Close()` that just calls `unix.Close()` to do that. But there is a risk that the fd will be closed a second time when `EventMetadata.File()` is called. For example, this code pattern:

```
data, err := pidFileDirNotify.GetEvent()
...
defer data.Close()
...
fileContent, err := ioutil.ReadAll(data.File())
```

When using `data.File()`, it will create a `os.File` with a finalizer: see [src/os/file_unix.go](https://cs.opensource.google/go/go/+/refs/tags/go1.17.1:src/os/file_unix.go;l=187):
```
runtime.SetFinalizer(f.file, (*file).close)
```

So when the `os.File` variable is out of scope, the garbage collector will close it, leading to a double close. The second close() could be harmless if the fd number is not reused: the `close()` syscall would just return `EBADF`. But if another fd is allocated, reusing the same fd number, then it would be closed.

This happened in https://github.com/kinvolk/inspektor-gadget/pull/283

In general, it's better to avoid mixing API with `fd int` and with `os.File`. The following code pattern works without double fd-close:
```
data, err := pidFileDirNotify.GetEvent()
...
dataFile := data.File()
defer dataFile.Close()
...
fileContent, err := ioutil.ReadAll(dataFile)
```

In this case, there is no double close because `dataFile.Close()` closes it one time and then [removes the finalizer](https://cs.opensource.google/go/go/+/refs/tags/go1.17.1:src/os/file_unix.go;l=260-261), so the garbage collector will not close it a second time.

To make it easier for users of the go-fanotify library, I suggest to remove the `EventMetadata.Close()` method and update the [example code](https://github.com/s3rj1k/go-fanotify/blob/master/cmd/main.go#L57) to use this:
```
dataFile := data.File()
defer dataFile.Close()
```

cc @rata @iaguis

**Comment by s3rj1k** [comment]
@alban Wow, did not expect that kinvolk uses this lib, thanks for detailed issue.
Are you planning on doing a PR with fix that you suggested?

**Comment by s3rj1k** [comment]
Also tagged a release to make go.mod prettier on importing side

**Comment by rata** [comment]
@s3rj1k thanks!
