### ISSUE TITLE
can't change the mount point

### ISSUE THREAD

**Issue by seyoatda** [s3rj1k/go-fanotify#7]
I've change the mountpoint from '/' to a custom directory. But it is still listening to root dir.

**Comment by s3rj1k** [comment]
@seyoatda Please consult https://man7.org/linux/man-pages/man7/fanotify.7.html
as this is most probably a configuration issue

**Comment by seyoatda** [comment]
already read the man page. So I can't listen to a directory without mounting it as  a mountpoint? Because I only want to watch certain directory's event. But whether I use `FAN_MARK_MOUNT` or `FAN_MARK_FILESYSTEM` flags, fanotify only listen to root dir, instead of the dir I define in `pathname`

**Comment by s3rj1k** [comment]
@seyoatda yes, You need to listen to a mountpoint and then filterout manually that you actually need, also bind-mounts are working, also overlayfs is working, somewhat.

It's been quite some time I've played with fanotify, so I could be wrong.

**Comment by s3rj1k** [comment]
@seyoatda Also if you want to listen for events of specific dirrectory without recursive events, you could just use inotify or dirrct pulling approach, fanotify library actually was created only to support recursive directory watching, as it is much cheaper to watch mountpoints with fanotify instead of using multiple inotify watchers.

**Comment by seyoatda** [comment]
> @seyoatda Also if you want to listen for events of specific dirrectory without recursive events, you could just use inotify or dirrct pulling approach, fanotify library actually was created only to support recursive directory watching, as it is much cheaper to watch mountpoints with fanotify instead of using multiple inotify watchers.

thanks for the reply. I'm using inotify right now. However I want to add the permission control features, so I try to switch to fanotify. Now I see that they work very differently on watching.
