### ISSUE TITLE
when i change mountpoint but still got data from other mount point message

### ISSUE THREAD

**Issue by INT2ECALL** [s3rj1k/go-fanotify#8]

**Comment by s3rj1k** [comment]
@INT2ECALL Please provide code example and a detailed scenario how to reproduce this issue

**Comment by INT2ECALL** [comment]
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/s3rj1k/go-fanotify/fanotify"
	"golang.org/x/sys/unix"
	"flag"
)

func main() {

	log.SetFlags(log.Lshortfile)

	notify, err := fanotify.Initialize(
		unix.FAN_CLOEXEC|
			unix.FAN_CLASS_NOTIF|
			unix.FAN_UNLIMITED_QUEUE|
			unix.FAN_UNLIMITED_MARKS,
		os.O_RDONLY|
			unix.O_LARGEFILE|
			unix.O_CLOEXEC,
	)
	if err != nil {
		log.Fatalf("%v\n", err)
	}
	
	var mountpoint string
	mp := flag.String("mp","/","mount point")
	flag.Parse()
	mountpoint = *mp

	fmt.Printf("mountpoint=%s", mountpoint)

	if err = notify.Mark(
		unix.FAN_MARK_ADD|
			unix.FAN_MARK_MOUNT,
		unix.FAN_ACCESS,
		unix.AT_FDCWD,
		mountpoint,
	); err != nil {
		log.Fatalf("%v\n", err)
	}

	f := func(notify *fanotify.NotifyFD) (string, error) {
		data, err := notify.GetEvent(os.Getpid())
		if err != nil {
			return "", fmt.Errorf("%w", err)
		}

		if data == nil {
			return "", nil
		}

		defer data.Close()

		path, err := data.GetPath()
		if err != nil {
			return "", err
		}

		dataFile := data.File()
		defer dataFile.Close()

		fInfo, err := dataFile.Stat()
		if err != nil {
			return "", err
		}

		mTime := fInfo.ModTime()

		if data.MatchMask(unix.FAN_ACCESS) {
			//if path == "/etc/inputrc" {
				return fmt.Sprintf("PID:%d %s - %v", data.GetPID(), path, mTime), nil
			//}
		}

		return "", fmt.Errorf("fanotify: unknown event")
	}

	for {
		str, err := f(notify)
		if err == nil && len(str) > 0 {
			fmt.Printf("%s\n", str)
		}

		if err != nil {
			fmt.Printf("error: %v\n", err)
		}
	}
}

**Comment by INT2ECALL** [comment]
`package main

import (
	"fmt"
	"log"
	"os"

	"github.com/s3rj1k/go-fanotify/fanotify"
	"golang.org/x/sys/unix"
	"flag"
)

func main() {

	log.SetFlags(log.Lshortfile)

	notify, err := fanotify.Initialize(
		unix.FAN_CLOEXEC|
			unix.FAN_CLASS_NOTIF|
			unix.FAN_UNLIMITED_QUEUE|
			unix.FAN_UNLIMITED_MARKS,
		os.O_RDONLY|
			unix.O_LARGEFILE|
			unix.O_CLOEXEC,
	)
	if err != nil {
		log.Fatalf("%v\n", err)
	}
	
	var mountpoint string
	mp := flag.String("mp","/","mount point")
	flag.Parse()
	mountpoint = *mp

	fmt.Printf("mountpoint=%s", mountpoint)

	if err = notify.Mark(
		unix.FAN_MARK_ADD|
			unix.FAN_MARK_MOUNT,
		unix.FAN_ACCESS,
		unix.AT_FDCWD,
		mountpoint,
	); err != nil {
		log.Fatalf("%v\n", err)
	}

	f := func(notify *fanotify.NotifyFD) (string, error) {
		data, err := notify.GetEvent(os.Getpid())
		if err != nil {
			return "", fmt.Errorf("%w", err)
		}

		if data == nil {
			return "", nil
		}

		defer data.Close()

		path, err := data.GetPath()
		if err != nil {
			return "", err
		}

		dataFile := data.File()
		defer dataFile.Close()

		fInfo, err := dataFile.Stat()
		if err != nil {
			return "", err
		}

		mTime := fInfo.ModTime()

		if data.MatchMask(unix.FAN_ACCESS) {
			//if path == "/etc/inputrc" {
				return fmt.Sprintf("PID:%d %s - %v", data.GetPID(), path, mTime), nil
			//}
		}

		return "", fmt.Errorf("fanotify: unknown event")
	}

	for {
		str, err := f(notify)
		if err == nil && len(str) > 0 {
			fmt.Printf("%s\n", str)
		}

		if err != nil {
			fmt.Printf("error: %v\n", err)
		}
	}
}`

**Comment by INT2ECALL** [comment]
`
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/s3rj1k/go-fanotify/fanotify"
	"golang.org/x/sys/unix"
	"flag"
)

func main() {

	log.SetFlags(log.Lshortfile)

	notify, err := fanotify.Initialize(
		unix.FAN_CLOEXEC|
			unix.FAN_CLASS_NOTIF|
			unix.FAN_UNLIMITED_QUEUE|
			unix.FAN_UNLIMITED_MARKS,
		os.O_RDONLY|
			unix.O_LARGEFILE|
			unix.O_CLOEXEC,
	)
	if err != nil {
		log.Fatalf("%v\n", err)
	}
	
	var mountpoint string
	mp := flag.String("mp","/","mount point")
	flag.Parse()
	mountpoint = *mp

	fmt.Printf("mountpoint=%s", mountpoint)

	if err = notify.Mark(
		unix.FAN_MARK_ADD|
			unix.FAN_MARK_MOUNT,
		unix.FAN_ACCESS,
		unix.AT_FDCWD,
		mountpoint,
	); err != nil {
		log.Fatalf("%v\n", err)
	}

	f := func(notify *fanotify.NotifyFD) (string, error) {
		data, err := notify.GetEvent(os.Getpid())
		if err != nil {
			return "", fmt.Errorf("%w", err)
		}

		if data == nil {
			return "", nil
		}

		defer data.Close()

		path, err := data.GetPath()
		if err != nil {
			return "", err
		}

		dataFile := data.File()
		defer dataFile.Close()

		fInfo, err := dataFile.Stat()
		if err != nil {
			return "", err
		}

		mTime := fInfo.ModTime()

		if data.MatchMask(unix.FAN_ACCESS) {
			//if path == "/etc/inputrc" {
				return fmt.Sprintf("PID:%d %s - %v", data.GetPID(), path, mTime), nil
			//}
		}

		return "", fmt.Errorf("fanotify: unknown event")
	}

	for {
		str, err := f(notify)
		if err == nil && len(str) > 0 {
			fmt.Printf("%s\n", str)
		}

		if err != nil {
			fmt.Printf("error: %v\n", err)
		}
	}
}


`

**Comment by INT2ECALL** [comment]
using pass mp="/etc" still get other directory message ,why? thank for help

**Comment by s3rj1k** [comment]
> using pass mp="/etc" still get other directory message ,why? thank for help

is "/etc" a separate mountpoint? does it show-up in `findmnt`?

**Comment by INT2ECALL** [comment]
TARGET                                SOURCE           FSTYPE      OPTIONS
/                                     /dev/sda5        ext4        rw,relatime,errors=remount-ro
├─/sys                                sysfs            sysfs       rw,nosuid,nodev,noexec,relatime
│ ├─/sys/kernel/security              securityfs       securityfs  rw,nosuid,nodev,noexec,relatime
│ ├─/sys/fs/cgroup                    tmpfs            tmpfs       ro,nosuid,nodev,noexec,mode=755
│ │ ├─/sys/fs/cgroup/unified          cgroup2          cgroup2     rw,nosuid,nodev,noexec,relatime,nsdelegate
│ │ ├─/sys/fs/cgroup/systemd          cgroup           cgroup      rw,nosuid,nodev,noexec,relatime,xattr,name=systemd
│ │ ├─/sys/fs/cgroup/perf_event       cgroup           cgroup      rw,nosuid,nodev,noexec,relatime,perf_event
│ │ ├─/sys/fs/cgroup/memory           cgroup           cgroup      rw,nosuid,nodev,noexec,relatime,memory
│ │ ├─/sys/fs/cgroup/devices          cgroup           cgroup      rw,nosuid,nodev,noexec,relatime,devices
│ │ ├─/sys/fs/cgroup/rdma             cgroup           cgroup      rw,nosuid,nodev,noexec,relatime,rdma
│ │ ├─/sys/fs/cgroup/freezer          cgroup           cgroup      rw,nosuid,nodev,noexec,relatime,freezer
│ │ ├─/sys/fs/cgroup/cpuset           cgroup           cgroup      rw,nosuid,nodev,noexec,relatime,cpuset
│ │ ├─/sys/fs/cgroup/net_cls,net_prio cgroup           cgroup      rw,nosuid,nodev,noexec,relatime,net_cls,net_prio
│ │ ├─/sys/fs/cgroup/cpu,cpuacct      cgroup           cgroup      rw,nosuid,nodev,noexec,relatime,cpu,cpuacct
│ │ ├─/sys/fs/cgroup/hugetlb          cgroup           cgroup      rw,nosuid,nodev,noexec,relatime,hugetlb
│ │ ├─/sys/fs/cgroup/pids             cgroup           cgroup      rw,nosuid,nodev,noexec,relatime,pids
│ │ └─/sys/fs/cgroup/blkio            cgroup           cgroup      rw,nosuid,nodev,noexec,relatime,blkio
│ ├─/sys/fs/pstore                    pstore           pstore      rw,nosuid,nodev,noexec,relatime
│ ├─/sys/fs/bpf                       none             bpf         rw,nosuid,nodev,noexec,relatime,mode=700
│ ├─/sys/kernel/debug                 debugfs          debugfs     rw,nosuid,nodev,noexec,relatime
│ ├─/sys/kernel/tracing               tracefs          tracefs     rw,nosuid,nodev,noexec,relatime
│ ├─/sys/fs/fuse/connections          fusectl          fusectl     rw,nosuid,nodev,noexec,relatime
│ └─/sys/kernel/config                configfs         configfs    rw,nosuid,nodev,noexec,relatime
├─/proc                               proc             proc        rw,nosuid,nodev,noexec,relatime
│ └─/proc/sys/fs/binfmt_misc          systemd-1        autofs      rw,relatime,fd=28,pgrp=1,timeout=0,minproto=5,maxproto=5
│   └─/proc/sys/fs/binfmt_misc        binfmt_misc      binfmt_misc rw,nosuid,nodev,noexec,relatime
├─/dev                                udev             devtmpfs    rw,nosuid,noexec,relatime,size=1972964k,nr_inodes=493241
│ ├─/dev/pts                          devpts           devpts      rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000
│ ├─/dev/shm                          tmpfs            tmpfs       rw,nosuid,nodev
│ ├─/dev/hugepages                    hugetlbfs        hugetlbfs   rw,relatime,pagesize=2M
│ └─/dev/mqueue                       mqueue           mqueue      rw,nosuid,nodev,noexec,relatime
├─/run                                tmpfs            tmpfs       rw,nosuid,nodev,noexec,relatime,size=400228k,mode=755
│ ├─/run/lock                         tmpfs            tmpfs       rw,nosuid,nodev,noexec,relatime,size=5120k
│ ├─/run/vmblock-fuse                 vmware-vmblock   fuse.vmware rw,relatime,user_id=0,group_id=0,default_permissions,all
│ ├─/run/snapd/ns                     tmpfs[/snapd/ns] tmpfs       rw,nosuid,nodev,noexec,relatime,size=400228k,mode=755
│ │ ├─/run/snapd/ns/curl.mnt          nsfs[mnt:[4026532629]]
│ │ │                                                  nsfs        rw
│ │ └─/run/snapd/ns/golangci-lint.mnt nsfs[mnt:[4026532630]]
│ │                                                    nsfs        rw
│ └─/run/user/1000                    tmpfs            tmpfs       rw,nosuid,nodev,relatime,size=400224k,mode=700,uid=1000,
│   ├─/run/user/1000/gvfs             gvfsd-fuse       fuse.gvfsd- rw,nosuid,nodev,relatime,user_id=1000,group_id=1000
│   └─/run/user/1000/doc              /dev/fuse        fuse        rw,nosuid,nodev,relatime,user_id=1000,group_id=1000
├─/snap/bare/5                        /dev/loop2       squashfs    ro,nodev,relatime
├─/snap/core18/2620                   /dev/loop1       squashfs    ro,nodev,relatime
├─/snap/core20/1778                   /dev/loop3       squashfs    ro,nodev,relatime
├─/snap/core18/2679                   /dev/loop4       squashfs    ro,nodev,relatime
├─/snap/gnome-3-34-1804/36            /dev/loop5       squashfs    ro,nodev,relatime
├─/snap/snapd/17950                   /dev/loop6       squashfs    ro,nodev,relatime
├─/snap/gnome-3-34-1804/77            /dev/loop7       squashfs    ro,nodev,relatime
├─/snap/gnome-3-38-2004/119           /dev/loop8       squashfs    ro,nodev,relatime
├─/snap/snap-store/599                /dev/loop9       squashfs    ro,nodev,relatime
├─/snap/gtk-common-themes/1534        /dev/loop10      squashfs    ro,nodev,relatime
├─/snap/gtk-common-themes/1535        /dev/loop11      squashfs    ro,nodev,relatime
├─/snap/snap-store/638                /dev/loop13      squashfs    ro,nodev,relatime
├─/snap/gnome-3-38-2004/106           /dev/loop12      squashfs    ro,nodev,relatime
├─/boot/efi                           /dev/sda1        vfat        rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset
├─/snap/go/10030                      /dev/loop14      squashfs    ro,nodev,relatime
├─/snap/curl/1435                     /dev/loop15      squashfs    ro,nodev,relatime
├─/snap/golangci-lint/114             /dev/loop16      squashfs    ro,nodev,relatime
└─/snap/core20/1822                   /dev/loop17      squashfs    ro,nodev,relatime

**Comment by s3rj1k** [comment]
So it works as expected, it's not a Go problem, this is how kernel fanotufy works, you do not have `etc` as a separate mount point, mount point for `etc` in your case is `/`. Only option is to filter by prefix.
